sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t caseybienvenu/sandbox-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true caseybienvenu/sandbox-docker-react npm run test
